### ISSUE TITLE
ep

### ISSUE THREAD

**Issue by dcancho** [JoseACd744/Cocktail_flutter#1]
el servicio tiene nulls

**Comment by JoseACd744** [comment]
ah KASJSAJSA, es que no me sale xd, ya le entend[i al servicio pero no me sale lo demas de listar y todo

**Comment by dcancho** [comment]
lo de listar es por el api. practicamente todo lo copié del modelo que hicimos ayer. el api puede devolver properties con null como valor. haz el check por cada map

**Comment by dcancho** [comment]
https://gist.github.com/dcancho/4d9bc9f729761f54e0d1ed48e50c7c4f
